name: Build Docker Image

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build Docker image
      run: |
        docker build \
          -t lxd-client:latest \
          --build-arg=LXD_VERSION=latest \
          .
    - name: Test Docker image
      run: |
        docker run --rm lxd-client:latest lxc --version

    - name: Push Docker image
      run: |
        docker tag lxd-client:latest kzn1990/lxd-client:latest
        docker push kzn1990/lxd-client:latest
